<?php
echo '<div style="position:absolute;width:100%;z-index:-2;top:0px;height:1600px;" class="background-top"><img src="./img/backgrounds/background-top.png" style="width:100%;height:1600px;"></div>';
echo '<div style="position:absolute;width:100%;z-index:-2;left:50px;" ><img src="./img/logos/jieyou_icon2.png" style="width:10%;height:auto;"></div>';
echo '<div style="position:absolute;width:100%;z-index:-3;height:100px;left:70%;" ><img src="./img/logos/banner.png" style="height:250px;width:auto;"></div>';
echo '<div style="width:65%;height:250px;"><div style="position:relative;left:30.77%;padding:30px;"><form method="post" action="jieyou_search.php"><input type="text" placeholder="输入关键词" name="keyword" style="padding:10px;font-size:14px;width:61.5%;vertical-align:middle;"><input type="button" id="submit-button" onclick="submit()" style="background-image:url(./img/logos/jieyou_search.png);height:40px;width:7.5%;vertical-align:middle;background-repeat:no-repeat;background-size:60px 60px;background-color:transparent;background-position:0px -10px;"><div style="margin-top:30px;"><select id="price" style="padding:5px;"><option selected="selected">价格</option><option>0-10</option><option>10-20</option><option>20-50</option><option>50以上</option></select><select style="padding:5px;margin-left:10px;"><option selected="selected">学部</option><option>理学部</option><option>信息与工程科学部</option><option>人文学部</option><option>社会科学学部</option><option>经济与管理学部</option></select><select style="padding:5px;margin-left:10px;"><option selected="selected">分类</option><option>专业课</option><option>通选课</option><option>公共必修课</option><option>课外书</option></select><span style="position:relative;left:25%;"><a href="jieyou_comsearch.php">高级检索</a></span></div></form></div></div>';
echo '<div style="width:100%;" id="block-1"><div id="cls" class="cls" style="width:15%;position:relative;margin-left:10%;float:left;">';
echo' <ul style="list-style-type:none;text-align:center;" id="clslist"><li style="padding-top:15px;padding-bottom:15px;background-color:#AA0000;color:white;font-weight:bold;" ><a href="jieyou.php" style="color:white;">全部分类</a></li></ul></div>';
echo '<div style="float:left;width:60%;display:flex;flex-wrap:no-wrap;" class="hot"><ul id="hotlist" style="padding-bottom:12px;padding-top:17px;list-style-type:none;color:#666;display:inline;border-bottom:3px solid #AA0000;"><li><a href="jieyou.php?cls=421" >高等数学</a></li><li><a href="jieyou.php?cls=43" >政治课教材</a></li><li><a href="jieyou.php?cls=25">西美史<span style="color:#AA0000;font-weight:strong;">&nbsp;&nbsp;hot</span></a></li><li><a href="jieyou.php?cls=41">计算机</a></li><li><a href="jieyou.php?cls=44">英语课教材</a></li><li ><a href="jieyou.php?cls=31" >自学自考</a></li><li><a href="jieyou.php?cls=3" >休闲读物</a></li></ul></div>';

?>
